spring:
  datasource:
    url: jdbc:postgresql://dpg-d0hos949c44c739o38mg-a.oregon-postgres.render.com:5432/desafio_api_db?user=desafio_api_db_user&password=ZFeeoQ4ru12daW8v5SKTvXBnRpaVjbd3
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect